@startuml
!includeurl https://raw.githubusercontent.com/Impassive/C4_puml/master/atc/atc.puml
'ORTHO
TD
STEREOTYPE_HIDE
ARROW_COLOUR Green
Group(g1, "group title") {
    system(c1, system1,text,desc)
    system(c2, system2,text,desc)
    system(c3, system3,text,desc)
    system(c4, system4,text,desc)
    system(c5, system5,text,desc)
    system(c6, system6,text,desc)
    ifRel2(u1,c1,c2,c3)
    ifClose2(u2,c2,c3)
}

' ifRel2(u3,c4,c5,c6)

@enduml