@startuml
!include atc/atc.puml
'ORTHO
TD
STEREOTYPE_HIDE
    system(c1, system1,text,desc)
    system(c2, system2,text,desc)
    system(c3, system3,text,desc)
    system(c4, system4,text,desc)
    system(c5, system5,text,desc)
    system(c6, system6,text,desc)

usecase "X" as u1
Rel(c1,u1," ")
Rel(u1,c2," ")
Rel(u1,c3," ")
@enduml