!includeurl https://raw.githubusercontent.com/Impassive/C4_puml/master/core/core.puml
'include ../core/core.puml
' ATC primary elements colour
' ##################################

' Waypoint
!define WAYPOINT_BG_COLOUR RoyalBlue
!define WAYPOINT_BD_COLOUR DarkSlateGray

' External Waypoint
!define EXTERNAL_WAYPOINT_BG_COLOUR SlateGray
!define EXTERNAL_WAYPOINT_BD_COLOUR DimGray

' Database
!define DATABASE_BG_COLOUR LightSteelBlue
!define DATABASE_BD_COLOUR DarkSlateGray

' ATC primary elements styling
' ##################################

skinparam rectangle<<waypoint>> {
    StereotypeFontColor ELEMENT_FONT_COLOUR
    FontColor ELEMENT_FONT_COLOUR
    BackgroundColor WAYPOINT_BG_COLOUR
    BorderColor WAYPOINT_BD_COLOUR
}

skinparam rectangle<<waypoint_external>> {
    StereotypeFontColor ELEMENT_FONT_COLOUR
    FontColor ELEMENT_FONT_COLOUR
    BackgroundColor EXTERNAL_WAYPOINT_BG_COLOUR
    BorderColor EXTERNAL_WAYPOINT_BD_COLOUR
}

skinparam database<<database>> {
    StereotypeFontColor ELEMENT_FONT_COLOUR
    FontColor ELEMENT_FONT_COLOUR
    BackgroundColor DATABASE_BG_COLOUR
    BorderColor DATABASE_BD_COLOUR
}

' ATC primary elements
' ##################################

' System
!define waypoint(x, label) rectangle "==label" <<waypoint>> as x
!define waypoint(x, label, text) rectangle "==label\n\n text" <<waypoint>> as x
!define waypoint(x, label, text, desc) rectangle "==label\n//<size:DESC_FONT_SIZE>[desc]</size>//\n\n text" <<waypoint>> as x

' System
!define waypoint_external(x, label) rectangle "==label" <<waypoint_external>> as x
!define waypoint_external(x, label, text) rectangle "==label\n\n text" <<waypoint_external>> as x
!define waypoint_external(x, label, text, desc) rectangle "==label\n//<size:DESC_FONT_SIZE>[desc]</size>//\n\n text" <<waypoint_external>> as x

' Database
!define database(x, label) database "==label" <<database>> as x
!define database(x, label, text) database "==label\n\n text" <<database>> as x
!define database(x, label, text, desc) database "==label\n//<size:DESC_FONT_SIZE>[desc]</size>//\n\n text" <<database>> as x


' PLSQL adoptation
' ##################################
'Waypoint element
!definelong plsql_system_gp(system_id, system_title, waypoint_id, waypoint_label)
System(system_id, system_title){
    waypoint(waypoint_id, waypoint_label)
}
!enddefinelong

!definelong plsql_system_gp(system_id, system_title, waypoint_id, waypoint_label, waypoint_text)
System(system_id, system_title){
    waypoint(waypoint_id, waypoint_label, waypoint_text)
}
!enddefinelong

!definelong plsql_system_gp(system_id, system_title, waypoint_id, waypoint_label, waypoint_text, waypoint_desc)
System(system_id, system_title){
    waypoint(waypoint_id, waypoint_label, waypoint_text, waypoint_desc)
}
!enddefinelong